version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - node/test
workflows:
  build-and-test:
    jobs:
      - build-and-test
